---
- hosts: all
  tasks:
    - name: Installs nginx web server
      apt: pkg=nginx state=installed update_cache=true
      notify:
        - start nginx

     ignore_errors: True

    - name: Remove index.html for host
      command: rm /var/www/html/index.nginx-debian.html
      when: php|success

    - name: Upload default index.html for host
      copy: src=static_files/index.html dest=/var/www/html/ mode=0644
      when: php|failed

  handlers:
    - name: start nginx
      service: name=nginx state=started  - name: Upload default index.php for host
      copy: src=static_files/index.php dest=/var/www/html/ mode=0644
      register: php
   
